export const BRAND_PREVIEW_PLANS = [
  {
    id: 'demo-1',
    plan: 'SP-10421',
    student: 'Aroha Williams',
    stage: 'Active',
    authorisationStatus: 'Authorised',
    agreementDate: '2026-02-12',
    amount: 4800,
    collected: 2400,
    remaining: 2400,
    overdue: 0,
    status: 'No Arrears',
    course: 'Diploma in Business',
    paymentAmount: 200,
    frequency: 'Weekly',
    daysInArrears: 0,
  },
  {
    id: 'demo-2',
    plan: 'SP-10438',
    student: 'James Chen',
    stage: 'Active',
    authorisationStatus: 'Setup in progress',
    agreementDate: '2026-03-04',
    amount: 3600,
    collected: 1200,
    remaining: 2400,
    overdue: 400,
    status: '1 - 15 Days',
    course: 'Certificate in IT',
    paymentAmount: 150,
    frequency: 'Weekly',
    daysInArrears: 9,
  },
  {
    id: 'demo-3',
    plan: 'SP-10390',
    student: 'Priya Patel',
    stage: 'Active',
    authorisationStatus: 'Setup in progress',
    agreementDate: '2026-01-18',
    amount: 7200,
    collected: 3600,
    remaining: 3600,
    overdue: 600,
    status: '16 - 30 Days',
    course: 'Bachelor of Nursing',
    paymentAmount: 300,
    frequency: 'Fortnightly',
    daysInArrears: 22,
  },
  {
    id: 'demo-4',
    plan: 'SP-10211',
    student: 'Daniel Ngata',
    stage: 'Active',
    authorisationStatus: 'Authorised',
    agreementDate: '2025-11-02',
    amount: 5400,
    collected: 1800,
    remaining: 3600,
    overdue: 900,
    status: '31 - 60 Days',
    course: 'New Zealand Diploma in Construction',
    paymentAmount: 225,
    frequency: 'Weekly',
    daysInArrears: 47,
  },
  {
    id: 'demo-5',
    plan: 'SP-10104',
    student: 'Sophie Laurent',
    stage: 'Active',
    authorisationStatus: 'Authorised',
    agreementDate: '2025-09-15',
    amount: 9600,
    collected: 2400,
    remaining: 7200,
    overdue: 1800,
    status: '61 - 90 Days',
    course: 'Graduate Diploma in Teaching',
    paymentAmount: 400,
    frequency: 'Monthly',
    daysInArrears: 73,
  },
  {
    id: 'demo-6',
    plan: 'SP-10088',
    student: 'Tane Rangi',
    stage: 'Cancelled',
    authorisationStatus: 'Cancelled',
    agreementDate: '2025-07-21',
    amount: 2400,
    collected: 400,
    remaining: 2000,
    overdue: 2000,
    status: '90+ Days',
    course: 'Certificate in Culinary Arts',
    paymentAmount: 100,
    frequency: 'Weekly',
    daysInArrears: 112,
  },
  {
    id: 'demo-7',
    plan: 'SP-10455',
    student: 'Emily Brooks',
    stage: 'Active',
    authorisationStatus: 'Authorised',
    agreementDate: '2026-04-09',
    amount: 1800,
    collected: 600,
    remaining: 1200,
    overdue: 0,
    status: 'No Arrears',
    course: 'Short Course — Digital Marketing',
    paymentAmount: 150,
    frequency: 'Weekly',
    daysInArrears: 0,
  },
];
